# Generated by Django 5.2 on 2026-06-19 12:39

import django.db.models.deletion
import workspace.tokens
import hashlib
import re
from django.db import migrations, models


def hash_existing_tokens(apps, schema_editor):
    Project = apps.get_model("workspace", "Project")
    ClientPortalSession = apps.get_model("workspace", "ClientPortalSession")
    sha256_pattern = re.compile(r"^[0-9a-f]{64}$")

    for project in Project.objects.all().iterator():
        if project.client_access_token and not sha256_pattern.fullmatch(project.client_access_token):
            project.client_access_token = hashlib.sha256(
                project.client_access_token.encode("utf-8")
            ).hexdigest()
            project.save(update_fields=["client_access_token"])

    for session in list(ClientPortalSession.objects.all()):
        if session.token and not sha256_pattern.fullmatch(session.token):
            old_token = session.token
            session.token = hashlib.sha256(old_token.encode("utf-8")).hexdigest()
            session.save(force_insert=True)
            ClientPortalSession.objects.filter(token=old_token).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='branddna',
            name='brand_feeling',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='project',
            name='client_access_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='client_access_revoked',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='clientportalsession',
            name='token',
            field=models.CharField(default=workspace.tokens.generate_hashed_portal_token, editable=False, max_length=128, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='project',
            name='client_access_token',
            field=models.CharField(default=workspace.tokens.generate_hashed_portal_token, max_length=128, unique=True),
        ),
        migrations.RunPython(hash_existing_tokens, migrations.RunPython.noop),
        migrations.CreateModel(
            name='SmartBrief',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveIntegerField(default=1)),
                ('positioning_statement', models.TextField(blank=True)),
                ('audience_profile', models.TextField(blank=True)),
                ('positioning_gap', models.TextField(blank=True)),
                ('tone_archetype', models.CharField(blank=True, max_length=255)),
                ('brand_archetype', models.CharField(blank=True, max_length=255)),
                ('brand_promise', models.TextField(blank=True)),
                ('visual_brief', models.TextField(blank=True)),
                ('tagline_options', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='smart_briefs', to='workspace.project')),
            ],
            options={
                'ordering': ('-version', '-updated_at'),
                'constraints': [models.UniqueConstraint(fields=('project', 'version'), name='unique_project_smart_brief_version')],
            },
        ),
    ]
