# Generated by Django 5.2 on 2026-06-20 06:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0002_branddna_brand_feeling_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscoveryDraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.JSONField(blank=True, default=dict)),
                ('current_step', models.PositiveSmallIntegerField(default=1)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('saved_at', models.DateTimeField(auto_now=True)),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='discovery_draft', to='workspace.project')),
            ],
        ),
    ]
